### ISSUE TITLE
Laravel 5.1 issue

### ISSUE THREAD

**Issue by ahmadazimi** [darrylkuhn/dialect#10]
I have a problem installing on Laravel 5.1:

`Your requirements could not be resolved to an installable set of packages.`

Doesn't support Laravel 5.1?

**Comment by darrylkuhn** [comment]
No it's written against larvael 4.2

**Comment by ahmadazimi** [comment]
So, do you have any plan to upgrade it to support 5.x? I think this is really useful to whom using Postgres and Postgis.

**Comment by darrylkuhn** [comment]
At some point yes - but not in the near future. I'm a L4.2 user so I haven't had time to sort through L5 and figure out how this needs to change to support it yet (I welcome any contributions though :)

**Comment by darrylkuhn** [comment]
Hey - I finally got around to taking care of this in the main repo

**Comment by ahmadazimi** [comment]
Good news :+1:
