### ISSUE TITLE
Migration file

### ISSUE THREAD

**Issue by kadnan** [darrylkuhn/dialect#13]
How can I set data type as `JSON` while creating migration?

**Comment by darrylkuhn** [comment]
unfortunately there is no mechanism for this using the SchemaBuilder (that I am aware of). However you can execute a statement as part of the migration like so (assuming you're using postgres 9.3 or later):

`DB::statement( "ALTER TABLE {$tableName} ADD COLUMN {$columnName} JSON" );`

Hope that helps
