### ISSUE TITLE
laravel5: take in account attribute casting

### ISSUE THREAD

**Issue by younes0** [darrylkuhn/dialect#2]
L5 eloquent models allows you to cast attributes: 

``` php
protected $casts = [
    'is_admin' => 'boolean',
    'my_json_column' => 'array',
];
```

the idea is that your lib takes `$casts` values so you don't need to declare $jsonColumns in models

**Comment by EspadaV8** [comment]
Could there be any instances where you might want laravels 'dumb' casting of JSON data to an array/object for a column and not this package? Or would should another cast be introduced? e.g. `jsond` ?

**Comment by EspadaV8** [comment]
Ah, looking at the code it wouldn't actually be possible to use this property, the part of Laravel that deals with it...

``` php
/**
 * Cast an attribute to a native PHP type.
 *
 * @param  string  $key
 * @param  mixed   $value
 * @return mixed
 */
protected function castAttribute($key, $value)
{
    if (is_null($value)) return $value;

    switch ($this->getCastType($key))
    {
        case 'int':
        case 'integer':
            return (int) $value;
        case 'real':
        case 'float':
        case 'double':
            return (float) $value;
        case 'string':
            return (string) $value;
        case 'bool':
        case 'boolean':
            return (bool) $value;
        case 'object':
            return json_decode($value);
        case 'array':
        case 'json':
            return json_decode($value, true);
        default:
            return $value;
    }
}
```

Doesn't call any external methods or provide any way to add new casts. The only way would be to override the method...

Actually, that might work out okay, but possibly not the best solution.... hmm

**Comment by darrylkuhn** [comment]
Conclusion on this? Looking to close out or implement if there's something to do here...

**Comment by younes0** [comment]
My first comment was confusing, please note that you can cast to json too (thanks to @EspadaV8)
You could do:

``` php
public function inspectJsonColumns()
{
    // merge jsonColumns with cast property
    $casted = array_keys(array_where($this->casts, function($k, $v) {
        return ($v === 'json')
    }));

    $this->jsonColumns = array_merge($this->jsonColumns, $casted);

    foreach ($this->jsonColumns as $col) {
        $this->hidden[] = $col;
        $obj = json_decode($this->$col);
        if (is_object($obj)) {
            foreach ($obj as $key => $value) {
                $this->flagJsonAttribute($key, $col);
                $this->appends[] = $key;
            }
        }
    }
}
```

**Comment by darrylkuhn** [comment]
This looks dead but if there is still a need please re-open or submit pull request. Thanks!
