### ISSUE TITLE
Why does the readme state "only supports PostgreSQL"

### ISSUE THREAD

**Issue by that0n3guy** [darrylkuhn/dialect#8]
I don't see anything in the code that is PostgreSQL specific.  Not only that, but I'm using this w/ mysql :).

You might want to change the readme.

**Comment by darrylkuhn** [comment]
At the time I there wasn't support for JSON data types in MySQL (searching quickly it looks like they're adding it into 5.7 which is currently in RC). 

To answer your question though there are bits and pieces that are Postgres-specific. For example the operators defined in $jsonOperators are specific to Postgres. Line 124 inside mutateAttribute() has some Postgres specific syntax, etc...

Once an MySQL 5.7 goes gold maybe an enterprising contributor will rework this library to support it _hint hint_ :) I used MySQL for years before moving to Postgres recently (specifically for JSON support)

**Comment by that0n3guy** [comment]
@darrylkuhn Your `$jsonOperators` could be used with postgres, but they aren't used in that way.  They are just used with implode/preg_split.  

As far as I can tell, there is nothing database specific about this package.  Line 124 has nothing to do with a database.

If you don't use any of your jsonOperators in my data (which mysql doesn't, it just store json as a string)... it just works fine.

**Comment by darrylkuhn** [comment]
Au contraire mon frère - 

Well technically you're right - line 124 is just doing string manipulation, however the `mutateAttribute()` function is used in a lot of ways including when constructing WHEREs for relations. Take the example below:

``` php
class Comments extends Model
{
    /*
    |----------------------------------------------
    | Example: Relation on Comments Model. Assume 
    | the model has a json column called details
    |----------------------------------------------
    */

    public function user()
    {
        return $this->hasOne( 'User', 'id', "details->>'user_id'" );
    }
}
```

In this case `mutateAttribute()` converts `"details->>'user_id'"` to `user_id` which resolves. Without that in place you would not be able to define a relation on a nested JSON element. 

The syntax (`->>'column'` in this case) is psql specific. 

Unless I am thinking about this wrong... can you define relations using MySQL?

**Comment by that0n3guy** [comment]
Right, so your dialect package isn't dependent on postgres, it has some postgres features.  It works perfectly fine w/ mysql (not sure about the relation side of things, but storing data works great).

**Comment by darrylkuhn** [comment]
Ok - well I'll update the README with a little note about that... Thanks for the feedback!
